# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [21]:
#Your code here

## Note: must referece the folder 'Data'!!

import pandas as pd
pd.read_csv('Data/Zipcode_Demos.csv')

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,COUNT MALE,4.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [28]:
# the above data is actually 2 tables merged into one big table, so we split them into
# df1 and df2

df1 = pd.read_csv('Data/Zipcode_Demos.csv', skiprows = [1], nrows = 45, usecols = [1,2])
df1

                     Average Statistics  Unnamed: 2
0                     JURISDICTION NAME   10005.800
1                    COUNT PARTICIPANTS       9.400
2                          COUNT FEMALE       4.800
3                        PERCENT FEMALE       0.404
4                            COUNT MALE       4.600
5                          PERCENT MALE       0.396
6                  COUNT GENDER UNKNOWN       0.000
7                PERCENT GENDER UNKNOWN       0.000
8                    COUNT GENDER TOTAL       9.400
9                  PERCENT GENDER TOTAL      80.000
10               COUNT PACIFIC ISLANDER       0.000
11             PERCENT PACIFIC ISLANDER       0.000
12                COUNT HISPANIC LATINO       2.000
13              PERCENT HISPANIC LATINO       0.105
14                COUNT AMERICAN INDIAN       0.000
15              PERCENT AMERICAN INDIAN       0.000
16             COUNT ASIAN NON HISPANIC       3.600
17           PERCENT ASIAN NON HISPANIC       0.437
18             COUNT WHITE NON HISPANIC       0.800
19           PERCENT WHITE NON HISPANIC       0.036
20             COUNT BLACK NON HISPANIC       2.600
21           PERCENT BLACK NON HISPANIC       0.181
22                COUNT OTHER ETHNICITY       0.400
23              PERCENT OTHER ETHNICITY       0.040
24              COUNT ETHNICITY UNKNOWN       0.000
25            PERCENT ETHNICITY UNKNOWN       0.000
26                COUNT ETHNICITY TOTAL       9.400
27              PERCENT ETHNICITY TOTAL      79.900
28       COUNT PERMANENT RESIDENT ALIEN       0.500
29     PERCENT PERMANENT RESIDENT ALIEN       0.061
30                     COUNT US CITIZEN       8.900
31                   PERCENT US CITIZEN       0.739
32           COUNT OTHER CITIZEN STATUS       0.000
33         PERCENT OTHER CITIZEN STATUS       0.000
34         COUNT CITIZEN STATUS UNKNOWN       0.000
35       PERCENT CITIZEN STATUS UNKNOWN       0.000
36           COUNT CITIZEN STATUS TOTAL       9.400
37         PERCENT CITIZEN STATUS TOTAL      80.000
38     COUNT RECEIVES PUBLIC ASSISTANCE       2.300
39   PERCENT RECEIVES PUBLIC ASSISTANCE       0.151
40    COUNT NRECEIVES PUBLIC ASSISTANCE       7.100
41  PERCENT NRECEIVES PUBLIC ASSISTANCE       0.649
42      COUNT PUBLIC ASSISTANCE UNKNOWN       0.000
43    PERCENT PUBLIC ASSISTANCE UNKNOWN       0.000
44        COUNT PUBLIC ASSISTANCE TOTAL       9.400

In [32]:
df2 = pd.read_csv('Data/Zipcode_Demos.csv', skiprows = 47)
df2

,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,48,10001,44,22,0.50,22,0.50,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
1,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
2,50,10003,1,1,1.00,0,0.00,0,0,1,...,1,100,0,0.00,1,1.00,0,0,1,100
3,51,10004,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,52,10005,2,2,1.00,0,0.00,0,0,2,...,2,100,0,0.00,2,1.00,0,0,2,100
5,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0.00,6,1.00,0,0,6,100
6,54,10007,1,0,0.00,1,1.00,0,0,1,...,1,100,1,1.00,0,0.00,0,0,1,100
7,55,10009,2,0,0.00,2,1.00,0,0,2,...,2,100,0,0.00,2,1.00,0,0,2,100
8,56,10010,0,0,0.00,0,0.00,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
9,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0.00,3,1.00,0,0,3,100

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [22]:
#Hint: here's a useful programming pattern to use.
try:
    #do something
except Exception as e:
    #handle your exception e

IndentationError: expected an indented block (<ipython-input-22-13f6e15364f1>, line 4)

In [23]:
#Your code here
try:
    pd.read_csv('Data/Yelp_Reviews_Corrupt.csv')
except Exception as e:
    print (e)

Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

In [35]:
# we break up the table whenever there is a failure row

for i in range(0,3000):
    try:
        df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows=i)
    except:
        print(f'failure at row: {i}')
        break
df01 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows=i-1)
df01

failure at row: 1962

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0.0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0.0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1.0,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3.0,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0.0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0.0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0.0,pfavA0hr3nyqO61oupj-lA,1.0,This place sucks. The customer service is horr...,2.0,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0.0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0.0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0.0,HkYqGb0Gplmmk-xlHTRBoA,1.0,The score should be negative. Its HORRIBLE. Th...,0.0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0.0,RgqWdZA4xR023iP3T6jVfA,5.0,I went there twice and I am pretty happy with ...,0.0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0.0,51RHs_V_fjuistnuKxNpEg,5.0,Finally! After trying many Mexican restaurants...,0.0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0.0,alI_kRKyEHfdHibYGgtJbw,1.0,I have to write a review on the Fractured Prun...,0.0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0.0,85DRIjwPJOTb4q0qOlBstw,1.0,I wish i could tell you all about the food but...,1.0,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0.0,GbiLIKmQPVCBtdNkTVdVSA,5.0,Wonderful! One of my favorite places. BBQ is e...,0.0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0.0,UaHgsL0xS4UnJ_iKqeOk_w,5.0,The price is about the same as Quizinos. The s...,0.0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0.0,c4zzAD1S6721Fh-acCBy-g,4.0,The food was ok. You get a lot of food for the...,0.0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0.0,TTBwocu2mvqJFJrwmJN0Sw,5.0,The staff were friendly and helpful. The food ...,1.0,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0.0,-CresnnXQSHrQ85Ogm-Pqw,5.0,The staff were very helpful. We painted potter...,0.0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0.0,U04YgYr4PiGUxB46J4xapg,2.0,Limited vegetarian options. Ordered Greek sala...,0.0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0.0,s9cpVj40VR_yl0lXbZQe6w,5.0,I trust my vehicles here. Comparable prices. M...,0.0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0.0,AJ0IglpYAp2D0daOlVGIdg,1.0,This place doesn't even deserve 1 star. Horrib...,18.0,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0.0,5D_MsAJHrMa8QKkpE3g1Sg,5.0,The butter burger was cooked perfectly and jui...,0.0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0.0,5bWN_IN8MQGjJ6_ZIXffDw,5.0,Best location ever! I love love love the manag...,0.0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0.0,RW_mYzHYfdqn6g7xVgIcKg,4.0,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0.0,SLA1YP9doUc8h-6Kd34QmA,1.0,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0.0,qxPiEGIHy5xyVy78avH5Rg,4.0,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0.0,q6ij-nz5d_hvdjuelho1pQ,5.0,Better service and much better prices than the...,0.0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0.0,66FSK2J1uHJqVI1Z8QiFGw,4.0,I love how they have no rice sushi options. Th...,0.0,Yy_iGXxLpL6tYDQoE-6XVg
...,...,...,...,...,...,...,...,...,...,...
1931,4929,MQJxekA2SN8kmoo-kiq1dw,0,2016-08-11,0.0,nSkln1WMfPcYMlu9_U_2Rg,4.0,Make sure you get her tomato salad now while i...,0.0,gqYegYGd-N4TLUile0CS8g
1932,4931,C3GUi1zAtJdDBWrPoPZjBQ,1,2016-08-11,1.0,y7L3g9JrkUbh07NnfUTX0Q,4.0,I love their beer. I love it. I should have co...,1.0,gqYegYGd-N4TLUile0CS8g
1933,4932,hyyy_yFDI3CJJaG3uROGBA,0,2016-08-11,0.0,Y3doD-V1_HE5HqkkVzqwkw,4.0,The most consistent place I've ever been to as...,0.0,gqYegYGd-N4TLUile0CS8g
1934,4933,OF19lUVQHj8pVaSACNewWg,0,2016-08-11,0.0,Ct3tfJWvJbS2NpMO48ruig,3.0,Been there a few times. I feel like I'm a both...,0.0,gqYegYGd-N4TLUile0CS8g
1935,4935,OA5Li3ySzhrbG_WvD_QGYA,0,2016-08-11,0.0,ihkFnY4-zKqf4xcE9kieSA,5.0,Best tacos for price there are. They brought f...,0.0,gqYegYGd-N4TLUile0CS8g
1936,4937,7m1Oa1VYV98UUuo_6i0EZg,0,2014-11-03,0.0,LnjBL-Iammf1_wb3uYVb1w,5.0,Best burgers in town hands down. Presentation ...,0.0,fdkfe69RTWTYws9oEcjRAQ
1937,4941,oa52t2Nfb7sOCqJE5M5hzg,1,2014-10-31,0.0,0ZkpokXX9Rk-1efEMgJ6ug,5.0,Cuisine for both meals was very amazing. Turn ...,0.0,fdkfe69RTWTYws9oEcjRAQ
1938,4942,j2bx_ctb_ED3zbfSaqhQmQ,0,2014-10-23,0.0,fpS7DeGecld3hJDVfLykEA,5.0,Service was and always is amazing. Food here i...,0.0,fdkfe69RTWTYws9oEcjRAQ
1939,4948,UO4HTFr0D_hEYvxrItx9vA,0,2015-12-28,0.0,VL38auKCiOYInYF2rYAd-g,1.0,It took almost an hour plus windows and floors...,0.0,L2XjX7843f9Jn09NTh0qvQ
1940,4951,NJ0RzuWd5xDqfJejYQZ65g,0,2009-12-10,0.0,YLQt2zCcXd_iJhzFdBBh3w,5.0,Wonderful food and service. I got the beet sal...,0.0,sNUD7INzDJYtuj6jAuIMRg
1941,4954,miMx3VNOW8qPJC5wEGaIOw,0,2013-06-26,0.0,Joh4pM9wb0EseqEITdMnAQ,5.0,Great food and people running it. I highly re...,NaN,NaN
1942,Again: get a Vermicelli bowl.,1,sNUD7INzDJYtuj6jAuIMRg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1943,4955,mlCDsdVFuZvRGrJTfQ6amw,0,2013-06-24,0.0,qeC6SaRgH4U6MxW0jE6R7w,4.0,Definitely worth the detour off of 80 to get s...,0.0,sNUD7INzDJYtuj6jAuIMRg
1944,4956,yLKoESPQ8BN7dn6ADzZicQ,0,2013-06-26,0.0,AJKCDiBmqFD4KjpbfOUHVg,4.0,Definitely one of the better options along gre...,NaN,NaN
1945,The menu is on eatcu's website.,1,sNUD7INzDJYtuj6jAuIMRg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946,4960,xrtyYnxgx7bTM3AEiwjWiA,0,2015-05-10,0.0,RhsBkpQpJn5wQnmcjo6HJA,5.0,The pantry was great came from a long trip had...,0.0,zL9ClwW6VnzJzsQVpMIXaQ
1947,4961,cQlmYFkJt1axuaKE3FiPxQ,0,2015-05-10,0.0,MdgbAedU24AL-2mXkbo_Jg,1.0,First time we stopped Monicals sat for eight m...,0.0,zL9ClwW6VnzJzsQVpMIXaQ
1948,4967,Kkpnsw5cuUwySbSKYUl7Iw,0,2017-12-03,0.0,8aX9VP1V0WVcuTN75mST6g,5.0,I have been here a few times and found the sta...,0.0,LTvChiWwJ7Y2hjBExB0a0Q
1949,4971,uD8SU0khj7Kn4BOrL-dwWw,1,2015-02-16,1.0,Cl129hSCUo-o41KjJQltcw,1.0,The line at the cutting table is ridiculous. T...,3.0,X72tQyDHRehGs6rwgt4EmQ
1950,4972,RWuYX5v7m7giMDmmhP7sVA,0,2016-06-16,0.0,bpr5_1x3RS3Dv4wLUa8B6Q,5.0,Lucas and his staff could not be more helpful ...,0.0,X72tQyDHRehGs6rwgt4EmQ
1951,4974,QhJT2fro3Dp1AaIVY7pgzQ,0,2017-06-25,0.0,kb4uFSvshz9Z2s8PcpekyA,1.0,The service was good and the lady who works th...,0.0,gOKk2aeRj49wAVGxGhdLZQ
1952,4982,K7lWdNUhCbcnEvI0NhGewg,0,2015-01-15,0.0,RMisEz2shYxuN_v_3nI2tw,4.0,I came to this buffet because of the ratings i...,0.0,cyR413IWtGe4VVuad4P-ow
1953,4984,A8UtlAQem2hPDe-UfsvndQ,0,2017-08-06,0.0,x_6xVjcOJL1OCcoQiEhF2g,5.0,This is the best Cajun food in Phoenix. Best E...,0.0,V2djoi-PqvPI1HcQUiy0lg
1954,4986,UCKwaY8_cgYZ4U0hZYWIUA,1,2014-01-28,0.0,u2rpsq1QFr66OURcIL-2_g,1.0,Do not use. Not reliable. Paid $1500 deposit i...,4.0,HLTht1eRoaRjnURKVnF31A
1955,4990,5jXwI9WpDxGDmzmkmE0RTg,0,2010-11-06,0.0,YGJKmW0h-qQD79qZPEf7Lw,5.0,There were 5 of us who tried Oishi. All of us...,1.0,tFa-r1pxZh04FjxNSEQgcQ
1956,4993,u8C8pRvaHXg3PgDrsUHJHQ,0,2016-08-08,0.0,gXmHGBSBBz2-uHdvGf4lZQ,2.0,just went to a retirement party upstairs and t...,1.0,tFa-r1pxZh04FjxNSEQgcQ
1957,4998,-9nai28tnoylwViuJVrYEQ,0,2015-03-22,0.0,u-zqCN_IXfypJIUzIVUuzw,5.0,Great restaurant and great atmosphere.,NaN,NaN
1958,I had an awesome great time with friends.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959,I loved the tapas and the excellent paella.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1960,I can't wait to come back soon.,0,otDVyX37h61WEbqPLEjCmQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
# we resume the table by skipping the failure row and start a df2 at the next row

for i in range(0,2000):
    try:
        df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', skiprows = 1962, nrows=i, names = df01.columns)
    except:
        print(f'failure at row: {i}')
        break
df02 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', skiprows = 1962, nrows=i-1, names = df01.columns)
df02

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,STAY AWAY FROM THIS PLACE!!!!!!,5,sDofYImMQQmu4Le5G9zmpQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3948,GAKFx4jFUtTOTpp_jDJnuA,0,2017-09-01,0,OUZWMw7EgO7D596pUelSlA,5,Nice relaxing atmosphere. Friendly service and...,1,6vJY67yve43Ijvn8RKVUow
2,3949,0QzCeORfF8EY34UODWRV9A,0,2017-09-03,0,7lbykaWFD8YBwT0mU1Rexw,4,Very pleased with our experience. Great off th...,0,6vJY67yve43Ijvn8RKVUow
3,3950,tlt8zNrZ6_A3DmXiM-cnBA,0,2016-06-12,0,Nd_soHwCYi8adcNIT2w9LQ,1,Wife went to this location and was horrible. N...,0,S0dnPb1OzaqdBSOxyLr7BQ
4,3952,XD0LjNuPPwJPsTAHecUh7A,0,2015-08-23,0,FUUTAr5CECrkfRa9Y2-MSg,1,Not baby friendly anymore.,NaN,NaN
5,Refused service for having an urban sized stro...,0,RsgRH4ixaiJ1zWnmXam6pQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3953,J64Yg3hQJXSI-ipnfJUkiw,0,2016-08-24,0,WyXXGm0ryKoAlLi68pq-kg,2,Paid for an Escalade but got picked up by an o...,4,RsgRH4ixaiJ1zWnmXam6pQ
7,3956,JJDxLSeHkEFPUrPCxEFp0w,0,2015-11-12,0,jSVDzcNUKrd3HpF8xGxScA,2,If you don't mind the mechanic's attitude prob...,1,RsgRH4ixaiJ1zWnmXam6pQ
8,3957,3k9treY8PmsZ42bKmuICgA,0,2015-10-11,0,OT7KEec2NRlCc8mGMZOf6A,2,Not sure why this place gets 4*... Food is meh...,1,RsgRH4ixaiJ1zWnmXam6pQ
9,3959,JJys4pp5xmf3bB4E3lmxRA,0,2015-11-07,0,3ARL8Y4ZPZ1qE9vEk2PH6w,1,It was decent before now it's terrible. Wings ...,1,RsgRH4ixaiJ1zWnmXam6pQ
10,3966,wrcfLni9nmJK46Wb4XMkaQ,0,2016-06-09,0,Bi6sJcqCyi3sJj2hyYMCIQ,5,This location is awesome. Juan & Lily work har...,0,peAIvDTWt8K5Ie06LKwI-Q
11,3971,4iB4J5fxd8tbYklDAnaD5g,0,2017-08-08,0,eYaDrVWjgRLuW_gGtYIPvA,4,I love the lazy river and the condo style room...,NaN,NaN
12,The reason for 4 stars and not 5 is the enforc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Another drawback is that 3 days in a row eithe...,1,E7PoXTT0MVc8xcayikQnsA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,3972,bjllusUsLq9zE4yZnLpOzg,1,2017-04-01,0,tVcGeNVOX9OZBeIaCwJ7Ng,5,Awesome fresh spiced just right Lebanese food....,1,E7PoXTT0MVc8xcayikQnsA
15,3978,Vd5n_Jv9vtvD6dzl3ReNWg,0,2017-07-01,0,rcczwv8dwm2q9PYOOoVSVQ,5,Seth Harrison commands an excellent crew. Seth...,0,Wn0H7qlBp7qxkTKO1yb7ng
16,3980,Qx2BnG2jpVV6XVFOYPfGcQ,0,2017-01-24,0,UcRaCYAPxYs5S6i3Y6FD7Q,5,Had an excellent experience with Greg Saxe...I...,0,f-7fj7zYD4Bt16X_fylhwg
17,3981,UdMrPZIXPTZfKhHBw_toKg,0,2017-01-24,0,dtL7CbqsBm-OPJM8t4jJ3g,5,Absolutely the best massage of my life. This ...,0,f-7fj7zYD4Bt16X_fylhwg
18,3991,C2zIZ9LRUsYvpbYyuESedA,0,2013-09-11,0,_2OuntrsiCCHlkLHdK_haQ,1,JUST TERRIBLE!,NaN,NaN
19,Called them and left a voice message after rea...,0,7v7fsVrUCYMYQ1oSSvesPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,3997,waJ8_8FGJC-j5uIP2im1-A,0,2014-05-15,0,hOCsdqpudPEBXw0aZ-ECDw,5,I will keep it simple. Vincent and crew are t...,0,phnJUC7oDXSM5FZxQOXfLA
21,3998,WyjxWKA0VKs6qiUUU9FOlA,0,2017-10-19,0,9P7FB4mrxmWIVzFQfkh-qA,4,I had a total roof replacement and had several...,0,phnJUC7oDXSM5FZxQOXfLA
22,4000,cX3N8kmxYoqiFzvQsTQ_wg,0,2014-03-17,0,KKk8cyEGGUVZeGyr4A81ww,1,I give this park one star and that's generous!...,0,lndbbUPdqDhrAbTo8KZ_Lw
23,4002,rPk01P-gHFZnBtRyfc7Wrg,1,2014-08-21,1,GD0hHJCuCSkvPHCowIs5Tw,1,The food is not good. Enchilada sauce taste ve...,0,eRqruHinDbcqiabrrwsJnw
24,4003,B1imfnKRvcotaYacPGUrLQ,0,2012-07-16,0,aVYEzil5IbO95WBfJHMDFg,5,Great food and service in good atmosphere. Re...,0,briM6b9_gnvVjft5jly42A
25,4022,TqL0ytKAucWdW2mR7EbayA,1,2014-02-20,0,Rp3L3s76vWc2VH_Ts18tsQ,5,Best Indian food I had in Pittsburgh.,NaN,NaN
26,Love the Saag! Highly Recommend it!,8,xdm-O1HveAvpwfz7rF1Hbw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,4027,ODJJdWPVThx0xQxbZlLE9w,0,2013-09-17,0,5Ud8MCxfpQDDMId3cOMmKQ,5,Madame Et Monsieur is an Excellent & clean fac...,NaN,NaN
28,I highly recommend it!,0,nLcQKpECIJzjE3VDM7HI_A,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,4028,iIwKW2cBAxjElE8eUzjwqA,1,2014-06-12,2,UOF3d3KodUR8BkRpQKcdHg,1,Burgers are good but that's what you expect wi...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1968,4432,5VXsbrqyJx0a4iaa43RNFA,1,2015-05-05,0,JZ6Hpwgtc-33wNfqpi_G7w,4,I've been here on several occasions. The food ...,and to top it all off,they have FRESH SQUEEZED OJ!! Omg. I love fre...
1969,1893,RhEvP5flF6KoPriMHmVYGg,0,2016-12-22,0,D5TQ1__MP9XK2TMFimt5Eg,1,I booked a king bed room to celebrate my husba...,so this was supposed to be a nice stay-cation...,Yumi advised me that my reservation was simpl...
1970,679,qCS7kgg2o5QxCvIhTUgzrQ,0,2013-05-30,1,veV2SXGTWHTAjP6pFVjS9A,4,Really cool boxing gym. Would have gotten 5 s...,staff is cool and the classes and instructors...,2
1971,175,YWd0I1BxSzFG61lSyC3IyQ,0,2010-11-18,0,j1eUfIWCc-IlZNmRlROqtQ,2,Disgraceland isn't bad,but it's definitely a bit overrated. Thier bi...,other times...
1972,Their menu takes an exceptionally creative loo...,layed-back,and they actually seem to care that you're th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1973,But like I said,all of that can change the next time you go i...,staff could be stuck-up and simply not care.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,Disappointingly enough,the one thing that you can count on that Disg...,is one hell-of-a cool name.,1,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN,NaN,NaN
1975,2060,B5E_Qp3R1q0oRlzbYaWIkQ,0,2016-07-11,0,54Als0ek4EPUDXhokp4A9Q,4,I have eaten here many times and it is always ...,0,SdxNjQk0I4qefOsKfJAz1g
1976,3041,ynyDiLHzTdf4du9xMhscxg,0,2015-10-30,0,M-0AaEDTwBSIv_HJu4-pjw,5,Rachael is an artist! I've been going to her f...,NaN,NaN
1977,Her studio is warm and relaxing! I recommend R...,0,lYXRVN2TJDEVB39G3HzplA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1978,4417,5nRJg6TN0k4AIh1NcCWiYA,0,2015-07-07,0,f6EOemx7YlGGoG-wjlZWkQ,5,The last few years my health has put me on the...,and wake up to see the sun everyday.,NaN
1979,After 6 months of searching for the right desi...,fantastic and put me at ease. I had a consult...,the shops master Script Artist. I gave him my...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1980,My guess is this is Robert Pho's shop and his ...,and I'm sure he isn't going put people on his...,clean,sterile studio,the lobby is plastered with awards,trophies,and endless news and magazine write ups.,NaN,NaN,NaN
1981,If you want a custom tattoo,don't look anywhere else.,0,DyllEmNvshuCxDXiiG00RQ,NaN,NaN,NaN,NaN,NaN,NaN
1982,914,roR1_DDlMk7mhi5_R6XVKA,0,2016-12-28,0,bCzzir-O8YmOdVKtinPARQ,5,Tried out this new location,and wow! Amazing. I will be back for sure! Ev...,0
1983,3413,ZilzayEdyk70SoI-wruJbg,0,2016-04-24,0,6lmRlkLRF0kSzVndIVAHYg,4,I used to frequent Congee Queen at least 3 tim...,NaN,NaN
1984,Portion sizes are great for sharing with a lar...,done the traditional way with green onion,Mango chicken and shrimp dish - unique flavou...,general Tao chicken,fried chilli turnip patties,spice and pepper salt squid,snow peas with garlic sauce - everything was...,NaN,NaN,NaN
1985,One star lost only because they had forgotten ...,but would have been nice if if arrived with e...,0,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN
1986,1828,Cr5CLpmVrmzFyz_RfQ6rmA,0,2017-05-24,0,CB5r-PrukLKAha8Ts4MI_w,4,This is my second time at scaddabush. I rememb...,a pizza,and a few sides. The carbonara was pretty goo...
1987,All in all,dinner at Scaddabush was a good experience! T...,0,Wzsduf0vEmr-Ih1H0Stvww,NaN,NaN,NaN,NaN,NaN,NaN
1988,465,dumO6I2X9g6dv_70NDWkmw,0,2014-02-15,0,xIhsEyb8LTuDXxrEaYBkGQ,2,We were hungry and didn't want to wait for a t...,NaN,NaN
1989,Grilled duck breast ($8 for 5 thin slices): It...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,Katsu don ($10): The rice was too burnt on arr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1991,Raku roll ($13): Their signature roll was smal...,crab meat and cucumber. The spicy sauce was g...,0,UGW-9bbBEB3eP1o6mWD_WA,NaN,NaN,NaN,NaN,NaN,NaN
1992,4870,lmxA0dJM0XsPCIHPXhEQ-g,2,2016-12-06,0,-9SndZXf480E329AB0auLw,5,The place was fully booked and we didn't make ...,so we sat at the full service bar. The bar te...,took wonderful care of us! Drinks were creati...
1993,3450,yP-6hIA3qGWbIz0p9zSaoA,0,2014-08-13,0,yXPEBweCjQtT1iYIU0ln-Q,3,3.5 stars,NaN,NaN
1994,We've been to Crave ever since it's opened. I'...,I've enjoyed my meals. I've also had pretty g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995,First time we came here,we were with a larger group,they had just opened a couple of weeks before...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1996,My previous visit,my husband ordered the lamb chops. They were ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1997,Most recently,I had the New York strip and my husband had t...,so I was the odd one out.,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', skiprows=len(df01)+len(df02), names=df01.columns)

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1218,ejaUQ1hYo7Q7xCL1HdPINw,0,2013-05-16,0,Tzh-u5ueYxEx-k2RAXe7cQ,2,I came here for lunch and was rather disappoin...,NaN,NaN
1,We were a large party of 8,but the restaurant was not very busy and serv...,etc.. and didn't really check in. Even gettin...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The food took a long time to come out. I had t...,which did not impress either.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I wanted to like this place,but would not recommend it based on my experi...,0,djSJ6a9gsLSdj-7BoyNNQA,NaN,NaN,NaN,NaN,NaN,NaN
4,766,F70couxLlxWDRZNIVHoIRA,0,2016-11-20,0,7veSLwiGteiTmKaL72XdBA,5,Ethical and mechanic don't always go together,as anyone who's been scammed can attest. So,needless to say I am so happy I found Al at b...
5,2268,egLYFnycp8ktxMCvilFdLw,0,2017-08-14,0,wH9ba46MH8dYb-m8pT3guA,5,John's place is:,NaN,NaN
6,* Fast - I was in and out in less than 10 minu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,* Friendly - I've never met someone so genuine...,so the experience becomes something special.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,* Fantastic - The photos are fabulous. He real...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Get to Chinatown,climb the stairs up to the studio,and you'll have the best looking passport pho...,1,XoiBk3HfY0F5WSBgDPZFog,NaN,NaN,NaN,NaN,NaN
10,4195,0UlMUHtEDgDMkycBQpoAew,0,2016-09-29,0,5cVvvSNgMaKHvURXhxyIIQ,5,Following our review,we immediately contacted by the general manag...,0
11,1335,FcJ7DkL-UKj8RLUi08lyfg,0,2010-02-13,16,FrbgYH9yL3g8GaIkNefLDg,1,NOT child-friendly in child-friendly Leslievil...,looking forward to a quiet lunch & a pint at ...,their bartender watched as I struggled to get...
12,Still hungry,thirsty,and well-deserving of a baby-break,we backtracked to longstanding Leslieville in...,and were warmly received.,NaN,NaN,NaN,NaN,NaN
13,BTW,I parked my baby stroller next to the owner's...,3,xAM4wCIVwH2k7_y8eayNYA,NaN,NaN,NaN,NaN,NaN,NaN
14,14,f5O7v_X_jCg2itqacRfxhg,0,2017-10-12,0,kS4hrhEScwB9V5JATYjvVQ,5,Sansotei serves some top notch ramen. They tak...,so my company of five had to wait outside for...,and even after writing everything down still ...
15,717,Swezz8vG_9woCkV30kdgKA,0,2012-03-07,0,RMB8LFNBKlWML_A_jS-yMg,4,I love it here!,NaN,NaN
16,But you really need to order the all you can e...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Seoul Grill recently revised their menu,so there are more options for different meats...,which are so yummy! Try to spicy pork belly (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,And remember when eating meat first order not ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,I must say it's really nice not having to driv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Oh and all the people who work here are so nic...,2,WgbbxTRIy7MwDKn7nL5WKQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1665,R5ZvZ97FDp2bD93CNKg-zQ,0,2013-07-29,1,mpNaGq0ylyDNf6JKYky69A,3,Coming to this place is like rolling the dice ...,0,N3nQ4CclmbNepoJmFCm7Ng
22,4063,6HdzmAatFoB8UDep4n9QIw,0,2017-03-08,1,ocpWvLrQbksUubB9CRX-SA,4,Joined them for national pancake day. Walked i...,stopped the waiter walking by and asked him ...,when still no one came asked another waiter A...
23,2034,R5sfMJeNBARIOT9OevJLkA,0,2016-07-29,0,hiDqMNV9daG77k8PwQU7iw,1,Worst company ever! The product is soap and wa...,1,8UPnHtRqG-xJJBYXMN3LPw
24,1836,TeL2_oZCI-eA1NMrznG58Q,0,2015-09-22,0,BWiq0ICztUNuhEgZDa8g_Q,2,Very messy store and expensive for what you g...,1,uU_ol_n14rgh8kuuZ--WSQ
25,1301,SYhiOIAvxBNHt5QEQpu8dg,0,2013-10-14,0,fhhHsaEO-TEkVyojvXJueA,5,We went to Avec Bistro for our anniversary in ...,even I would order the lamb. We had some que...,0
26,2237,lIdzQkSWB8HpX0ac4isKnA,2,2012-05-11,2,sQJH9sibaB8YiEiE4-Rysg,5,First of all,Pico Madama has the Moxie crew but is in a ne...,NaN
27,My husband has been going to Ama for about a y...,healthy,and lustrous as it's ever been.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,I would absolutely recommend Ama if you are lo...,2,hvZ5o9YNJJ-TVCcdT42VoQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,4156,qMJyOW1FdPOf8sli8DIq_A,0,2015-01-10,0,dGCac3rFvfsxmabrMLcf8g,5,Delicious Crepes! Delice has the feel and menu...,0,FfqX7xdQY80nbkdNoeh_6Q
...,...,...,...,...,...,...,...,...,...,...
1498,Starting off with drinks,Bamburger serves beer,wine,and old-fashioned Stewart's soda,but what is a burger joint without milkshakes...,including the usual vanilla and chocolate sus...,as well a special flavour each day for the ni...,NaN,NaN,NaN
1499,The menu is varied,offering up soup,salads,sandwiches and desserts,as well as a kid's menu,but almost everyone here is in it for the bur...,from the type of bun,burger patty (beef,chicken,turkey
1500,We went with the Bambamburger ($11.50),which is 2/3 of a pound of prime ground chuck,and the chicken burger ($9.95) for myself,on whole-wheat buns. Both of us outfitted our...,including mushrooms,onions,garlic mayo and cheese sauce for the Bambambu...,and avocado,chipotle mayo,dill pickles and jalapeno peppers for the chi...
1501,Bamburger serves up great burgers,fries and shakes at a fairly good price,although if you go a little overboard with th...,you might quickly end up with a $20 burger,without realizing it. The service was friendl...,and the atmosphere was very comfortable and n...,NaN,NaN,NaN,NaN
1502,If you are hunting for a real deal on a burger,Bamburger might not be what you are looking for,but if you are more on the adventurous side,and want to have fun creating your own burger...,Bamburger will deliver.,8,YHWsLBS8jzZiPjKHMFOaAA,NaN,NaN,NaN
1503,3225,iyyWYpWm8X-6i7kBR3JHuw,0,2014-01-27,0,yLKMQNn8VE3CEDX-TF5CfA,1,Tried to attend a recent basketball game. Purc...,two parents and two kids. Arrived 45 min earl...,1
1504,4674,4KfDcE9iU2isFpoaKeDpgw,0,2012-06-14,0,rFH9iSvRmdm5LtDdsYwwpA,5,Great place to take your kids and interesting ...,0,9gYbRvijurhrnC6yPRlaUw
1505,4719,P4Plzlfm4uJjNmH3wY4W1Q,0,2014-01-14,0,IobIRp1mGJiLg4B6wHAvqQ,2,While I will continue to eat at this establish...,I will only do so because it is the closet Ch...,otherwise I would completely avoid this place...
1506,3440,nW45ez1L6U4PsYhV1BTrGQ,0,2012-05-19,0,abStF7f3_IyfZmOP82baZQ,5,H&F Jewellery is amazing!,NaN,NaN
1507,I had given my husband some ideas of engagemen...,a friend of ours recommended H&F.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1508,The customer service here is great - they are ...,attentive,honest and the prices are very reasonable! My...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1509,We went back for our wedding bands and I worke...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1510,We've recommended 5 other friends to H&F - the...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1511,Go to H&F for all your jewellery needs - you w...,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1512,4812,e13SEvJud_vgeDR_doL4sQ,0,2013-03-01,0,lUV1KEm4cl4mluSEFharFQ,4,We loved the food. The service was good and we...,0,NW6gHZ8PlYl1STK1A1Ixeg
1513,1970,9NBkIExYYz3w9O5JdzDOMA,0,2013-11-03,0,RT20_fUNJJNqMNvvjviNbQ,1,Hit or miss. I used these guys twice in a day ...,no call nothing. So I call the dispatch to le...,$20 to go 4 miles? I'll be renting a car tomo...
1514,689,BTcY04QFiS1uh-RpkR7rAg,1,2013-06-02,0,6_A58CCY8SHB7r-Wu7-A5g,5,Came here with my 2 year old daughter for our ...,she asked if everything was ok. We old her w...,great seating!
1515,4874,t0T_4MM4EUHbCzBTF11FHA,0,2016-08-14,0,KqQwNyfoFiJOw911mrULIg,5,Great little restaurant. Not to many tables an...,which is awesome. We had the Pad Thai and the...,0
1516,564,5XYR6doRa5Nj1JMfSDei6A,1,2016-06-14,0,xlGJkxoIBl8XH8wVsPZpnw,5,Always great friendly service and fresh baked ...,NaN,NaN
1517,Highly recommend the custard cakes they are th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1518,The rice flour cake is also really good and a ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1519,The bean cakes are great here too! orange,almond,and a few others I have tried are all good.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1520,Can't go wrong with Nova Era,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1521,3458,aLcFhMe6DDJ430zelCpd2A,0,2013-10-02,0,kwiEG_KCpDB6aK5fTSM7iw,2,We were expecting amazing Thai food after all ...,NaN,NaN
1522,This was disappointing.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1523,First off,it was really awkward sitting on the benches ...,as people walked past us while to wait for ou...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1524,Second,when we were seated,it was so loud. It felt like we were in a hig...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1525,Finally - Food was mediocre. I was extremely d...,but it wasn't flavourful.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1526,Wasn't worth the hype,unfortunately.,1,PkRFSQgSfca9Tamq7b2LdQ,NaN,NaN,NaN,NaN,NaN,NaN
1527,4206,WdBWhGe4Siqg3IYTc4_K4A,0,2016-08-15,0,O0ttxNGxHKtD8Cnnwc_j1g,1,Sunday at 8p. Not many people here at all. We ...,and no one came to take our drink order. We w...,0